<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>FirstClassFinance</RootNamespace>    
        <UserSecretsId>1ec2ff66-c813-4c7d-b00f-81f2593e4576</UserSecretsId>    
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
        <PackageReference Include="MailKit" Version="4.16.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="11.0.0-preview.3.26207.106" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    </ItemGroup>

</Project>
